[package]
name = "rusty-transit-relay"
version = "0.1.1"
edition = "2021"

[profile.release]
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false
strip = true


[dependencies]
anyhow = "1.0.95"
bytes = "1.9.0"
clap = { version = "4.5.26", features = ["derive"] }
env_logger = "0.11.6"
futures = "0.3.31"
hex = "0.4.3"
log = "0.4.25"
multimap = "0.10.0"
rust-fsm = "0.7.0"
thiserror = "2.0.12"
tokio = { version = "1.43.0", features = ["full"] }
winnow = "0.7.12"
